apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-service
  labels:
    name: mongoexpress-service
spec:
  tls:
    - hosts:
      - myhost.com
      secretName: myapp-secret-tls
  rules:
  - host: myhost.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mongoexpress-service
            port: 
              number: 8081
---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: base 64 encoded cert
  tls.key: base 64 encoded key


